# Generated by Django 3.1 on 2021-01-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210104_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='useriiiiiiiiiii',
        ),
    ]
