# Generated by Django 3.1 on 2021-01-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210104_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='useriiiiiiiiiii',
            new_name='user',
        ),
    ]
